server.port=8081

omdb.api.base-url=https://www.omdbapi.com/
omdb.api.key=73370347


spring.data.mongodb.uri=mongodb+srv://CreditCardUsers:mypass@cluster.bhq7tfs.mongodb.net/MoviesHere
spring.data.mongodb.database=MoviesHere

